### ISSUE TITLE
Suggestion: add "files" to the package.json template

### ISSUE THREAD

**Issue by sompylasar** [lirantal/create-node-lib#6]
- **Library Version**: code at b48b68a

Related: https://twitter.com/bitandbang/status/1088787376967700480

**Comment by lirantal** [comment]
Hi Ivan,

Having a whitelist is always preferable over blacklists.
I wonder though if this is something that most people will overlook and when they publish a package it will miss some files that they'd add to `lib/` or `src/` for example, to only find out about it later from users or such.

What do you think?

**Comment by lirantal** [comment]
Let's add it, and:
* Let's also add structure to the project so that it will not miss important files by default. Let's create a `src/` directory that will source the index.js export and add that to files
* Perhaps we can update the contributing guidelines to also include this information in a section about publishing a package

WDYT?

**Comment by sompylasar** [comment]
:+1:

Wanted to show you this https://github.com/sompylasar/ts-build-tools/blob/fc5622b/src/tasks/init.js but now realized I seem to have forgotten to add "files" there, too. :sweat_smile: 

Here's the structure it generates:
<img src="https://user-images.githubusercontent.com/498274/51798367-a3175500-21c5-11e9-9413-344d9a698384.JPG" width="200" />

**Comment by alemagio** [comment]
Hi, is someone working on this?

**Comment by lirantal** [comment]
Not at all, go ahead @alemagio
